/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'robxpatrick' at '19/05/15 20:20' with Gradle 2.3
 *
 * @author robxpatrick, @date 19/05/15 20:20
 */

import spock.lang.Specification
import spock.lang.Unroll

class CalculatorSpec extends Specification {

    @Unroll
    def 'add method should return #result for an input of a String #input'() {
        setup:
        Calculator calculator = new Calculator()
        expect:
        result == calculator.add(input)
        where:
        result | input
        0      | null
        0      | ''
        1      | '1'
        3      | '1,2'
        3      | ' 1 , 2 '
        21     | '1,2, 3,4, 5, 6'
    }

    @Unroll
    def 'add method should return #result for an input of a String #input with newline'() {
        setup:
        Calculator calculator = new Calculator()
        expect:
        result == calculator.add(input)
        where:
        result | input
        0      | null
        0      | ''
        1      | '1'
        3      | '1\n2'
        3      | ' 1 \n 2 '
        21     | '1\n2\n 3\n4, 5, 6'
    }

//    def 'add method should throw exception if the number is negative'() {
//        setup:
//        Calculator calculator = new Calculator()
//        given:
//        def result = calculator.add( '-1')
//        then:
//        result | input
//
//    }
}
